openapi: 3.0.3
info:
  title: Lab6 API
  version: 1.0.0
  description: Swagger docs for Lab6-INTPROG
servers:
  - url: http://localhost:4000
paths:
  /:
    get:
      summary: Health check
      tags:
        - Health
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: API is running
